const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),name=url.pathname.slice(1)||'index.html';
 if(name==='supabaseClient.js') {res.setHeader('Content-Type','text/javascript');res.end(`window.movioSupabase={from:()=>({select:()=>({order:async()=>{await new Promise(r=>setTimeout(r,50));return location.search.includes('empty')?{data:[]}:location.search.includes('failure')?{error:{message:'Offline'}}:{data:[{id:'current',name:'Current scooter',price:2299,category:'Scooter label',category_key:'electric-scooters',stock:5,free_delivery:true,active:true}]};}})})};`);return;}
 try {let body=fs.readFileSync(path.join(root,name));if(name.endsWith('.html'))body=body.toString().replace(/<script src="https:[^>]*><\/script>/g,'').replace('<head>',`<head><script>localStorage.setItem('movio-data-v1',JSON.stringify({products:[{id:'deleted',name:'Deleted bicycle',price:1566,stock:2}],orders:[]}));localStorage.setItem('movio-cart',JSON.stringify([{id:'deleted',quantity:1},{id:'current',quantity:2}]));</script>`).replace('</body>',`<script>addEventListener('load',async()=>{await MovioStore.catalogReady;const cards=[...document.querySelectorAll('.managed-product')];const deleted=cards.some(card=>card.textContent.includes('Deleted bicycle'));let ok=!deleted;if(location.search.includes('empty'))ok=ok&&cards.length===0&&MovioStore.getCatalogStatus()==='ready'&&!document.getElementById('catalogEmpty').hidden&&document.getElementById('catalogSyncMessage').hidden;else if(location.search.includes('failure'))ok=ok&&cards.length===0&&MovioStore.getCatalogStatus()==='error'&&!document.getElementById('catalogSyncMessage').hidden&&/[\u10A0-\u10FF]/.test(document.getElementById('catalogSyncMessage').textContent)&&!document.getElementById('catalogSyncMessage').textContent.includes('???');else{ok=ok&&cards.length===1&&cards[0].textContent.replace(/[^0-9]/g,'').includes('2299')&&cartStore.items.length===1&&cartStore.items[0].id==='current';applyCatalogFilter('electric-bikes');ok=ok&&cards[0].hidden;applyCatalogFilter('electric-scooters');ok=ok&&!cards[0].hidden;}document.body.setAttribute('data-regression',ok?'PASS':'FAIL');});</script></body>`);
 res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.html')?'text/html':'text/css');res.end(body);}catch{res.writeHead(404);res.end();}
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));for(const query of ['', '?empty=1', '?failure=1']){
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'movio-catalog-'));
 const output=await new Promise((resolve,reject)=>{const child=spawn(process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run',`--user-data-dir=${profile}`,'--dump-dom','--virtual-time-budget=3000',`http://127.0.0.1:${server.address().port}/${query}`],{windowsHide:true});let out='';child.stdout.on('data',v=>out+=v);child.on('error',reject);child.on('close',()=>resolve(out));});
 assert(output.includes('data-regression="PASS"'),`Browser scenario ${query||'success'} failed: ${output.slice(-2500)}`);
 }console.log('PASS headless Chrome: stale bicycle absent, scooter 2299 displayed, category filters, cart reconciliation, empty results show empty state, failed fetch shows Georgian error without stale cards');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.close());
